# application properties
apiUrl: http://localhost:#{'${server.port:8080}'}/api

info:
  date: 1987-09-01T23:55:15Z
  version: Local

### Loads the React Bundle from your local webpack dev server or from the Spring Boot resources
#react-bundle:
react-bundle: http://localhost:8081

# spring boot properties
spring:
  h2:
    console:
      enabled: true
      path: /console/
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
