apiUrl: http://localhost:#{'${server.port:8080}'}/api
spring:
  jpa:
    show-sql: false
logging:
  file: application.log
  level:
     org.springframework.web: DEBUG
     org.springframework.security: DEBUG
     org.hibernate: ERROR