apiUrl: http://localhost:#{'${server.port:8080}'}/api
react-bundle:
spring:
  jpa:
    show-sql: false
logging:
  file: application.log
  level:
     org.springframework.web: INFO
     org.springframework.security: INFO
     org.hibernate: ERROR

facebook:
 client:
   accessTokenUri: https://graph.facebook.com/oauth/access_token
   userAuthorizationUri: https://www.facebook.com/dialog/oauth
   scope: email
   tokenName: oauth_token
   authenticationScheme: query
   clientAuthenticationScheme: form
 resource:
   userInfoUri: https://graph.facebook.com/me?fields=id,name,email,picture

info:
  git: https://github.com/MannanM/corporate-game-share