# application properties
apiUrl: http://localhost:#{'${server.port:8080}'}/api

### Loads the React Bundle from your local webpack dev server or from the Spring Boot resources
#react-bundle:
react-bundle: http://localhost:8081

# spring boot properties
spring:
  h2:
    console:
      enabled: true
      path: /console/

facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
